### ISSUE TITLE
你这是一种传播盗版书的行为

### ISSUE THREAD

**Issue by zhengxiaowai** [jkchao/book#1]
请删除该 repo，或者转成私有的 repo。

利益无关，请自重。

**Comment by mrtanuky** [comment]
不管怎样，我已经report了
随便翻了一下，比如里面的Node.js实战 下面大字水印：图灵社区会员 quqingtao 专享 尊重版权
用盗版低调得了，出来四处传播就不好了

**Comment by LearnShare** [comment]
请尊重正版，自行删除该项目 😆

**Comment by LoveNuo13** [comment]
嗯 我已经删了

**Comment by jkchao** [comment]
本该低调。

**Comment by wellls** [comment]
已举报

**Comment by zhengxiaowai** [comment]
大家散了吧，已经删除了

**Comment by wellls** [comment]
1. 提交历史中还是能获取到盗版书籍。
2. ISSUE 的 ‘一个’ 建议改为 ‘一种’ 。

**Comment by zhengxiaowai** [comment]
@jkchao 还是请处理一下 commit 中还是存在的问题。

**Comment by Dendim0n** [comment]
six six six

**Comment by mxdhqm** [comment]
@jkchao  commit记录中仍能查看，删除该repo

**Comment by LearnShare** [comment]
删除 repo 重建一个同名的吧
